name: Daily Space Rebuild
on:
  schedule:
    # Runs at midnight Pacific Time (8 AM UTC)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - mteb/leaderboard/*
      - mteb/benchmarks/benchmarks.py

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Factory Rebuild
        run: |
          curl -X POST \
            "https://huggingface.co/api/spaces/mteb/leaderboard/restart?factory=true" \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}"
